name: SecureSDLC
run-name: "[SecureSDLC] Ref:${{ github.ref_name }} Event:${{ github.event_name }}"

on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [main]

jobs:
  securesdlc-umbrella:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: nautilus-wraith/securesdlc-umbrella/.github/workflows/securesdlc-umbrella.yml@release-stable
    secrets:
      SEMGREP_APP_URL: ${{ secrets.SEMGREP_APP_URL }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SDLC_SLACK_NOTIFICATIONS: ${{ secrets.SDLC_SLACK_NOTIFICATIONS }}
